### ISSUE TITLE
Shouldn't we call get_estimator_gradients(X)  instead of _get_estimator_gradients(X)  here?

### ISSUE THREAD

**Issue by NikolayLutsyak** [neuro-ml/edr-gp#19]
https://github.com/neuro-ml/edr-gp/blob/59fb432009d9d5ad400da8dcf1d15a204409963a/edrgp/edr.py#L29

**Comment by mibel** [comment]
The difference that internally (during fit) we have already preprocessed (i.e. normalized data), so we use 
` _get_estimator_gradients(self, X, prepocess=False)` 

But sometimes we may want to get gradients after fitting (e.g. to visualize gradients or to analyze them somehow). In that case, we have to preprocess data, so public method ` get_estimator_gradients` should be used. This method internally calls `_get_estimator_gradients(self, X, prepocess=True)` (so X will be normalized internally and then passed to the GP model).

**Comment by NikolayLutsyak** [comment]
Oh, I understand, thanks!
