### ISSUE TITLE
This function is never called. Should it be removed?

### ISSUE THREAD

**Issue by NikolayLutsyak** [neuro-ml/edr-gp#27]
https://github.com/neuro-ml/edr-gp/blob/d802306a92a6d18363bd90704954ff8136a9ca72/edrgp/edr.py#L99

**Comment by NikolayLutsyak** [comment]
I made a mistake, sorry

**Comment by mibel** [comment]
It's used there isn't it?
https://github.com/neuro-ml/edr-gp/blob/d802306a92a6d18363bd90704954ff8136a9ca72/edrgp/edr.py#L110
```
    def get_estimator_gradients(self, X):
        X = check_array(X)
        return self._get_estimator_gradients(X, True)

    def _get_estimator_gradients(self, X, prepocess=False):
        if prepocess:
            X = self._preprocessing_transform(X)
```

**Comment by NikolayLutsyak** [comment]
Yes, but method `get_estimator_gradients` is never called too. Look at issue #19

**Comment by mibel** [comment]
As discussed in #19, we can use `get_estimator_gradients` to obtain gradients after fit, so I'm closing the issue
